GET http://localhost:4000/categories/


###


POST http://localhost:4000/categories/
Content-Type: application/json

{
    "name": "Vacation",
    "description": "Holiday rentals, trips, and travel services."
  }